---
# tasks file for ec2_creation
- name: Create Zookeeper instance
  ec2:
    region: "{{ec2_config.region}}"
    zone: "{{ec2_config.zone}}"
    keypair: "{{ec2_config.keypair}}"
    instance_type: "{{ec2_config.instance_type}}"
    image: "{{ec2_config.image}}"
    vpc_subnet_id: "{{ec2_config.vpc_subnet_id}}"
    group: "{{ec2_config.group}}"
    assign_public_ip: "{{ec2_config.assign_public_ip}}"
    volumes:
      - device_name: /dev/sda1
        volume_size: "{{ec2_config.volume_size}}"
        delete_on_termination: true
#    count: "{{ec2_config.count}}"
    count: 3
    wait: yes
    instance_tags:
      # Name: "{{ec2_config.instance_tag_name}}"
      Name: Ansible_Zookeeper_jay
  register: ec2
