#Create the instance
- hosts: localhost
  # user: ec2user
  user: centos
  connection: local
  gather_facts: false
  vars_files:
    - vars/all.yml
  roles:
    - ec2_create_zk
    - ec2_create_broker
    - ec2_create_C3
    - ec2_create_ksql
    - ec2_create_connect
    - ec2_create_SR
    # - server



# Environment setup.
# - name: Set JMX_TEST
#   template:
#     src: jmx_test.sh.j2
#     dest: /etc/profile.d/jxm_test.sh
#     mode: 0644
#
# export  AWS_SECRET_ACCESS_KEY='alUDjeLhPwDnJhi5YB81o21lcaSMECyyGBFgmZfz'
# export AWS_ACCESS_KEY_ID='AKIAXFOLVZORDR2EOO6L'
#
# - name: echo AWS_SECRET_ACCESS_KEY
#   shell: echo 'AWS_SECRET_ACCESS_KEY'
#   register: jvm
# - debug: msg="the echo was {{ jvm.stdout }}"
#
# - set_fact:
    # common_role_completed: true
